// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ReuseDescriptions: typeof import('./src/components/reuseDescriptions/index.vue')['default']
    ReuseEcharts: typeof import('./src/components/reuseEcharts/index.vue')['default']
    ReuseForm: typeof import('./src/components/reuseForm/index.vue')['default']
    ReusePagination: typeof import('./src/components/reusePagination/index.vue')['default']
    ReuseTable: typeof import('./src/components/reuseTable/index.vue')['default']
    ReuseUpload: typeof import('./src/components/reuseUpload/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
